# -*- coding: utf-8 -*-
"""directory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gMooXBtpR4fY0kdERCLuSbBStYJ_5Sv9
"""

tum_kisiler=list()
tel_liste= list()
isimler= list()
soyisimler= list()
def menu():
  print("==============================")
  print("Yeni kişi eklemek: 1")
  print("Kişi silmek: 2")
  print("Kişi Bul:3")
  print("Kişi Düzenle :4")
  print("Programdan Çıkış : 5")
  print("==============================")
  a=int(input("Sayı giriniz: "))
  if a == 1:
    yeni_kisi_ekle()
  elif a ==2:
    kisi_silmek()
  elif a == 3:
    kisi_bul()
  elif a == 4:
    kisi_duzenle()
  elif a == 5:
   return programdan_cikis()

  return True  
def yeni_kisi_ekle():
  ad=input("Adınızı ve giriniz: ")
  soyad=input("Soyadınızı giriniz: ")
  tel_no=input("Telefon numaranızı giriniz: ")
  flag = kontrol(ad,soyad,tel_no)
  if flag == True:
    tum_kisiler.append(ad+" "+soyad+ " "+tel_no)
    tel_liste.append(tel_no)
    isimler.append(ad)
    soyisimler.append(soyad)
    print("Başarı ile kişi eklendi.")
    print(tum_kisiler)
    print(tel_liste)
  elif flag == False:
    print("{} numara daha önce kaydedilmiş.".format(tel_no))

def kontrol(ad,soyad,tel_no):
  for i in tel_liste :
    if i == tel_no:
      return False
  return True
def kisi_silmek():
  silmek=input("Silmek istediğiniz telefon numarasını giriniz: ")
  for j in tel_liste:
    if j == silmek:
      index=tel_liste.index(silmek)

      tum_kisiler.pop(index)
      tel_liste.pop(index)
      isimler.pop(index)
      soyisimler.pop(index)
      print(tum_kisiler)
      print(tel_liste)
      print(isimler)
      print(soyisimler)
      print("Silme işlemi başarı ile tamamlandı")

def kisi_bul():
  print("İsim = 1")
  print("Soyisim= 2")
  print("Telefon numarası= 3")
  secenek=int(input("İsim,soyisim veya telefon numarası seçiniz: "))
  if secenek == 1:
    isim=input("Aranacak ismi yazınız: ")
    for k in isimler:
      if k == isim:
        indeks=isimler.index(isim)

        print(tum_kisiler[indeks])
    
  elif secenek == 2:
    soyisim= input("Aranacak soyismi giriniz: ")
    for k in soyisimler:
      if k == soyisim:
        indeks=soyisimler.index(soyisim)
        print(tum_kisiler[indeks])

  elif secenek == 3:
    tel=int(input("Aranacak telefon numarasını giriniz: "))
    for k in tel_liste:
      if k == tel:
        indeks=tel_liste.index(tel)

        print(tum_kisiler[indeks])

def kisi_duzenle():
  print("İsim = 1")
  print("Soyisim= 2")
  print("Telefon numarası= 3")
  secenek=int(input("İsim,soyisim veya telefon numarası seçiniz: "))

  if secenek == 1:
    isim=input("Aranacak ismi yazınız: ")
    for k in isimler:
      if k == isim:
        indeks=isimler.index(isim)
        yeni_isim= input("Yeni ismi giriniz: ")
        tum_kisiler[indeks]=yeni_isim +" "+soyisimler[indeks]+" "+tel_liste[indeks]
        isimler[indeks]=yeni_isim
        
        print(tum_kisiler)
        print(isimler)


  elif secenek == 2:
    soyisim= input("Aranacak soyismi giriniz: ")
    for k in soyisimler:
      if k == soyisim:
        indeks=soyisimler.index(soyisim)
        yeni_soyisim=input("Yeni soyismi giriniz: ")
        tum_kisiler[indeks]= isimler[indeks]+" "+yeni_soyisim+" "+tel_liste[indeks]
        soyisimler[indeks]=yeni_soyisim
        print(tum_kisiler)
        print(soyisimler)

  elif secenek == 3:
    tel=input("Aranacak telefon numarasını giriniz: ")
    for k in tel_liste:
      if k == tel:
        indeks=tel_liste.index(tel)
        yeni_tel=input("Yeni telefon numarasını giriniz: ")
        tum_kisiler[indeks]=isimler[indeks]+" "+soyisimler[indeks]+" "+yeni_tel
        tel_liste[indeks]=yeni_tel
        print(tum_kisiler)
        print(tel_liste)  

def programdan_cikis():
  top=len(tum_kisiler)
  print("{} kişi kayıtlı,programdan çıkarsanız, tüm veriler silinecektir.".format(top))
  sor=input("Programdan çıkmak istediğinizden emin misiniz?(evet/hayır): ")
  if sor == "evet":
    return False
  elif sor == "hayır" :
    return True
  else :
    print("Yanliş girdiniz")
    return False   
  
flag =True
while (flag):
 flag= menu()