{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "directory",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyO/3R4YhZsVrCA/sbF5FwmV"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZbSC4UczjW24"
      },
      "source": [
        "tum_kisiler=list()\n",
        "tel_liste= list()\n",
        "isimler= list()\n",
        "soyisimler= list()\n",
        "def menu():\n",
        "  print(\"==============================\")\n",
        "  print(\"Yeni kişi eklemek: 1\")\n",
        "  print(\"Kişi silmek: 2\")\n",
        "  print(\"Kişi Bul:3\")\n",
        "  print(\"Kişi Düzenle :4\")\n",
        "  print(\"Programdan Çıkış : 5\")\n",
        "  print(\"==============================\")\n",
        "  a=int(input(\"Sayı giriniz: \"))\n",
        "  if a == 1:\n",
        "    yeni_kisi_ekle()\n",
        "  elif a ==2:\n",
        "    kisi_silmek()\n",
        "  elif a == 3:\n",
        "    kisi_bul()\n",
        "  elif a == 4:\n",
        "    kisi_duzenle()\n",
        "  elif a == 5:\n",
        "   return programdan_cikis()\n",
        "\n",
        "  return True  \n",
        "def yeni_kisi_ekle():\n",
        "  ad=input(\"Adınızı ve giriniz: \")\n",
        "  soyad=input(\"Soyadınızı giriniz: \")\n",
        "  tel_no=input(\"Telefon numaranızı giriniz: \")\n",
        "  flag = kontrol(ad,soyad,tel_no)\n",
        "  if flag == True:\n",
        "    tum_kisiler.append(ad+\" \"+soyad+ \" \"+tel_no)\n",
        "    tel_liste.append(tel_no)\n",
        "    isimler.append(ad)\n",
        "    soyisimler.append(soyad)\n",
        "    print(\"Başarı ile kişi eklendi.\")\n",
        "    print(tum_kisiler)\n",
        "    print(tel_liste)\n",
        "  elif flag == False:\n",
        "    print(\"{} numara daha önce kaydedilmiş.\".format(tel_no))\n",
        "\n",
        "def kontrol(ad,soyad,tel_no):\n",
        "  for i in tel_liste :\n",
        "    if i == tel_no:\n",
        "      return False\n",
        "  return True\n",
        "def kisi_silmek():\n",
        "  silmek=input(\"Silmek istediğiniz telefon numarasını giriniz: \")\n",
        "  for j in tel_liste:\n",
        "    if j == silmek:\n",
        "      index=tel_liste.index(silmek)\n",
        "\n",
        "      tum_kisiler.pop(index)\n",
        "      tel_liste.pop(index)\n",
        "      isimler.pop(index)\n",
        "      soyisimler.pop(index)\n",
        "      print(tum_kisiler)\n",
        "      print(tel_liste)\n",
        "      print(isimler)\n",
        "      print(soyisimler)\n",
        "      print(\"Silme işlemi başarı ile tamamlandı\")\n",
        "\n",
        "def kisi_bul():\n",
        "  print(\"İsim = 1\")\n",
        "  print(\"Soyisim= 2\")\n",
        "  print(\"Telefon numarası= 3\")\n",
        "  secenek=int(input(\"İsim,soyisim veya telefon numarası seçiniz: \"))\n",
        "  if secenek == 1:\n",
        "    isim=input(\"Aranacak ismi yazınız: \")\n",
        "    for k in isimler:\n",
        "      if k == isim:\n",
        "        indeks=isimler.index(isim)\n",
        "\n",
        "        print(tum_kisiler[indeks])\n",
        "    \n",
        "  elif secenek == 2:\n",
        "    soyisim= input(\"Aranacak soyismi giriniz: \")\n",
        "    for k in soyisimler:\n",
        "      if k == soyisim:\n",
        "        indeks=soyisimler.index(soyisim)\n",
        "        print(tum_kisiler[indeks])\n",
        "\n",
        "  elif secenek == 3:\n",
        "    tel=int(input(\"Aranacak telefon numarasını giriniz: \"))\n",
        "    for k in tel_liste:\n",
        "      if k == tel:\n",
        "        indeks=tel_liste.index(tel)\n",
        "\n",
        "        print(tum_kisiler[indeks])\n",
        "\n",
        "def kisi_duzenle():\n",
        "  print(\"İsim = 1\")\n",
        "  print(\"Soyisim= 2\")\n",
        "  print(\"Telefon numarası= 3\")\n",
        "  secenek=int(input(\"İsim,soyisim veya telefon numarası seçiniz: \"))\n",
        "\n",
        "  if secenek == 1:\n",
        "    isim=input(\"Aranacak ismi yazınız: \")\n",
        "    for k in isimler:\n",
        "      if k == isim:\n",
        "        indeks=isimler.index(isim)\n",
        "        yeni_isim= input(\"Yeni ismi giriniz: \")\n",
        "        tum_kisiler[indeks]=yeni_isim +\" \"+soyisimler[indeks]+\" \"+tel_liste[indeks]\n",
        "        isimler[indeks]=yeni_isim\n",
        "        \n",
        "        print(tum_kisiler)\n",
        "        print(isimler)\n",
        "\n",
        "\n",
        "  elif secenek == 2:\n",
        "    soyisim= input(\"Aranacak soyismi giriniz: \")\n",
        "    for k in soyisimler:\n",
        "      if k == soyisim:\n",
        "        indeks=soyisimler.index(soyisim)\n",
        "        yeni_soyisim=input(\"Yeni soyismi giriniz: \")\n",
        "        tum_kisiler[indeks]= isimler[indeks]+\" \"+yeni_soyisim+\" \"+tel_liste[indeks]\n",
        "        soyisimler[indeks]=yeni_soyisim\n",
        "        print(tum_kisiler)\n",
        "        print(soyisimler)\n",
        "\n",
        "  elif secenek == 3:\n",
        "    tel=input(\"Aranacak telefon numarasını giriniz: \")\n",
        "    for k in tel_liste:\n",
        "      if k == tel:\n",
        "        indeks=tel_liste.index(tel)\n",
        "        yeni_tel=input(\"Yeni telefon numarasını giriniz: \")\n",
        "        tum_kisiler[indeks]=isimler[indeks]+\" \"+soyisimler[indeks]+\" \"+yeni_tel\n",
        "        tel_liste[indeks]=yeni_tel\n",
        "        print(tum_kisiler)\n",
        "        print(tel_liste)  \n",
        "\n",
        "def programdan_cikis():\n",
        "  top=len(tum_kisiler)\n",
        "  print(\"{} kişi kayıtlı,programdan çıkarsanız, tüm veriler silinecektir.\".format(top))\n",
        "  sor=input(\"Programdan çıkmak istediğinizden emin misiniz?(evet/hayır): \")\n",
        "  if sor == \"evet\":\n",
        "    return False\n",
        "  elif sor == \"hayır\" :\n",
        "    return True\n",
        "  else :\n",
        "    print(\"Yanliş girdiniz\")\n",
        "    return False   \n",
        "  \n",
        "flag =True\n",
        "while (flag):\n",
        " flag= menu()\n"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}